language: java

jdk: openjdk8

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a
  - cd ../..

env:
  global:
    - CODECOV_TOKEN=:9b841d48-6afe-4ed1-bdea-aa84673c57ec

script: mvn verify -Ptest-consumer,test-business

after_success:
  - bash <(curl -s https://codecov.io/bash)
