language: java

jdk: openjdk8

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a
  - cd ../..

script: "mvn cobertura:cobertura -P test-consumer,test-business"

after_success:
  - bash <(curl -s https://codecov.io/bash)
